version: '3.8'
services:
  mobihub:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mobihub
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    restart: always
